# Generated by Django 3.0.6 on 2020-08-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('registration_status', models.CharField(choices=[('P', 'P'), ('R', 'R')], max_length=10, null=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
